app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
        path('map/', views.map),
        path('sightings/', views.index,name='index'),
        path('sightings/stats/', views.stats, name='stats'),
        path('sightings/add/', views.create_new_sighting, name='Create New Sighting'),
        path('sightings/<Unique_Squirrel_ID>/', views.update_sighting, name='Update Sighting'),
        ]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    ]

app/models.py
from django.db import models

from django.utils.translation import gettext as _


# Create your models here.

class Squirrel(models.Model):

    X_Latitude = models.FloatField(
        help_text=_('X-Latitude of Squirrel'),
        default=None,
    )

    Y_Longitude = models.FloatField(
        help_text=_('Y-Longitude of Squirrel'),
        default=None,
    )

    Unique_Squirrel_ID = models.CharField(
        max_length=100,
        help_text=_('Unique ID of squirrel'),
        primary_key=True,
        default=None,
        )

    PM = 'PM'
    AM = 'AM'
    SHIFT_CHOICES = [
            (PM, _('PM')),
            (AM, _('AM')),
    ]

    Shift = models.CharField(
        max_length=2,
        help_text=_('Shift of squirrel'),
        choices=SHIFT_CHOICES,
        default=AM,
    )

    Date = models.DateField(
        help_text=_('Date of record'),
        default=None,
    )

    ADULT = 'Adult'
    JUVENILE = 'Juvenile'

    AGE_CHOICES = (
        (ADULT, _('Adult')),
        (JUVENILE, _('Juvenile')),
    )

    Age = models.CharField(
        max_length=15,
        help_text=_('Age of squirrel'),
        choices=AGE_CHOICES,
        blank=True,
        null=True,
    )

    GRAY = 'Gray'
    CINNAMON = 'Cinnamon'
    BLACK = 'Black'

    COLOR_CHOICES_PRIMARY = (
        (GRAY,_( 'Gray')),
        (CINNAMON, _('Cinnamon')),
        (BLACK, _('Black')),
    )

    Primary_Fur_Color = models.CharField(
        max_length=15,
        help_text=_('Primary fur color of squirrel'),
        choices=COLOR_CHOICES_PRIMARY,
        blank=True,
        null=True,
    )

    GROUND_PLANE = 'Ground Plane'
    ABOVE_GROUND = 'Above Ground'

    LOCATION_CHOICES = (
        (GROUND_PLANE, _('Ground Plane')),
        (ABOVE_GROUND, _('Above Ground')),
    )
    
    Location = models.CharField(
        max_length=50,
        help_text=_('Location of squirrel'),
        choices=LOCATION_CHOICES,
        blank=True,
        null=True,
    )

    Running = models.BooleanField(
        help_text=_('Is the squirrel running?'),
        default=False,
    )

    Chasing = models.BooleanField(
        help_text=_('Is the squirrel chasing?'),
        default=False,
    )  

    Climbing = models.BooleanField(
        help_text=_('Is the squirrel climbing?'),
        default=False,
    )

    Eating = models.BooleanField(
        help_text=_('Is the squirrel eating?'),
        default=False,
    )

    Foraging = models.BooleanField(
        help_text=_('Is the squirrel foraging?'),
        default=False,
    )

    Other_Activity = models.TextField(
        help_text=_('Other activities?'),
        blank=True,
    )

    Kuks = models.BooleanField(
        help_text=_('Does the squirrel have kuks?'),
        default=False,
    )

    Quaas = models.BooleanField(
        help_text=_('Does the squirrel have quaas?'),
        default=False,
    )

    Moans = models.BooleanField(
        help_text=_('Does the squirrel have moans?'),
        default=False,
    )

    Tail_Flags = models.BooleanField(
        help_text=_('Does the squirrel have tail flags?'),
        default=False,
    )

    Tail_Twitches = models.BooleanField(
        help_text=_('Does the squirrel have tail twitches?'),
        default=False,
    )

    Approaches = models.BooleanField(
        help_text=_('Does the squirrel have approaches?'),
        default=False,
    )

    Indifferent = models.BooleanField(
        help_text=_('Is the squirrel indifferent?'),
        default=False,
    )

    Runs_From = models.BooleanField(
        help_text=_('Does the squirrel run from?'),
        default=False,
    )

    def __str__(self):
        return self.Unique_Squirrel_ID

app/forms.py
from django.forms import ModelForm
from django.views.generic.edit import UpdateView
from .models import Squirrel

class CreateNewForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = '__all__'


class UpdateForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = [
            'X_Latitude',
            'Y_Longitude',
            'Unique_Squirrel_ID',
            'Shift',
            'Date',
            'Age',
        ]

app/views.py
from django.shortcuts import render

from .models import Squirrel

from django.shortcuts import get_object_or_404

from django.http import HttpResponseRedirect

from .forms import CreateNewForm

from .forms import UpdateForm

from django.http import HttpResponse

# Create your views here.

def index(request):
    squirrels = Squirrel.objects.all()
    context = {
            'squirrels': squirrels,
            }
    return render(request, 'app/index.html',context)

def map(request):
    squirrels = Squirrel.objects.all()
    plot = Squirrel.objects.order_by('?')[:100]
    context = {
            'plot': plot,
            }
    return render(request, 'app/map.html',context)

def update_sighting(request, Unique_Squirrel_ID):
    instance = get_object_or_404(Squirrel, Unique_Squirrel_ID=Unique_Squirrel_ID)
    if request.method  == 'POST':
        form = UpdateForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/sightings/')
        else:
            return render(request, 'app/update.html', {'form':'form.errors'})
    else:
        form = UpdateForm(instance=instance)
        return render(request, 'app/update.html', {'form': form})    

def create_new_sighting(request):
    if request.method  == 'POST':
        form = CreateNewForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/sightings/')
        else:
            return render(request, 'app/create_new.html', {'form':'form.errors'})
    else:
        form = CreateNewForm()
        return render(request, 'app/create_new.html', {'form': form})

def stats(request):
    squirrels = Squirrel.objects.all()
    total_number = len(squirrels)
    am_shift = Squirrel.objects.filter(Shift='AM').count()
    adult_count = Squirrel.objects.filter(Age='Adult').count()
    gray_count = Squirrel.objects.filter(Primary_Fur_Color = 'Gray').count()
    ground_count = Squirrel.objects.filter(Location = 'Ground Plane').count()

    context = {
            'total_number': total_number,
            'am_shift': am_shift,
            'adult_count': adult_count,
            'gray_count': gray_count,
            'ground_count': ground_count,
            }
    return render(request, 'app/stats.html',context)

app/templates/app/create_new.html
<!doctype html>
<html>
	<head>
		<meta charset='utf8'>
		<style>
		body {
 			margin: 2;
			font-family: cursive, sans-serif;
			font-size:18px;
			line-height:2;
			color: DarkSlateGray;
			background-image: url('https://wallpapermemory.com/uploads/786/squirrel-background-hd-1440x900-311648.jpg');
			background-attachment: fixed;
			background-size: cover;
		}
		</style>
	</head>
	<body>
		<h1 style="color: DarkSlateGray; font-family: cursive, sans-serif; line-height:1;">Create Your Spot:</h2>
		<form method="post">
   			{% csrf_token %}
			{% if form.non_field_errors %}
        			<div class="form-group text-error">
					{{ form.non_field_errors }}
        			</div>
			{% endif %}	
   			{% for field in form.visible_fields %}
        			{{ field.help_text}}
        			{{ field }}
				<br>
        			{% if field.errors %}
            				<span>{{ field.errors|striptags }}</span>
        			{% endif %}
   			{% endfor %}
			<br>
   			<input type="submit" value="Submit">
		</form>
		<p><a href="{% url 'app:index' %}" style="color:GhostWhite;"><button type="button">Go Back to Index</button></a></p>
</html>

app/templates/app/detail.html
<html>
        <body>
	  Details of the Sighting:
	 <br> - Latitude: {{ squirrel.X_Latitude }}
	 <br>- Longitude: {{ squirrel.Y_Longitude }}
	 <br>- Unique Squirrel ID: {{ squirrel.Unique_Squirrel_ID }}
	 <br>- Shift: {{ squirrel.Shift }}
	 <br>- Date: {{ squirrel.Date }}
	 <br>- Age: {{ squirrel.Age }}
        </body>
</html>

app/templates/app/index.html
<!doctype html>
<html>
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h3 class="text-white">Squirrel Sightings, Inc. is all about tracking squirrels for you!</h3>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'app:stats' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Click Here to See Squirrel Sightings Statistics</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
	<br>
	<div class="navbar navbar-dark bg-dark shadow-sm">
          <div class="container d-flex justify-content-between">
           <a href="/map/" class="navbar-brand d-flex align-items-center">
             <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Click Here to See Squirrel Distributions on Map</strong>
           </a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
	  </div>
        </div>
	<br>
        <div class="navbar navbar-dark bg-dark shadow-sm">
         <div class="container d-flex justify-content-between">
          <a href="{% url 'app:Create New Sighting'%}" class="navbar-brand d-flex align-items-center">
             <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Click Here to Create a New Sighting of Squrriel</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
         </div>
	</div>
</header>

<head>
	<style type="text/css">
	body {
	 background-image: url('https://wallpapermemory.com/uploads/786/squirrel-background-hd-1440x900-311648.jpg');
	 background-attachment: fixed;
	 background-size: cover;
	}
	</style>
	<br>
        <h3 class="text-white">Below is a list of all the sightings:</h3>
        <ul class="list-unstyled"></ul>
	<div class="panel-body" style="height: 400px; overflow-y:scroll">	        
		<span>
		<ul>
                        {% for squirrel in squirrels %}
                <li>Unique Squirrel ID: {{ squirrel.Unique_Squirrel_ID }}
			<br>	Date: {{squirrel.Date}}
	 		<br><a href="{% url 'app:Update Sighting' squirrel.Unique_Squirrel_ID %}">See Details & Update</a></li>
			<br>
		{% endfor %}

		</ul>
		</span>
        </div>
		</body>
</head>


</html> 

app/templates/app/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
	    40.782091,
            -73.964285,
	];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sqr in plot %}
          var point_lat_lon = [{{ sqr.Y_Longitude }}, {{ sqr.X_Latitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

app/templates/app/stats.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  border-collapse: collapse;
  border: 2px solid rgb(200,200,200);
  letter-spacing: 1px;
  font-size: 0.8rem;
}
td, th {
  border: 1px solid rgb(190,190,190);
  padding: 10px 20px;
}

th {
  background-color: rgb(235,235,235);
}

td {
  text-align: center;
}

tr:nth-child(even) td {
  background-color: rgb(250,250,250);
}

tr:nth-child(odd) td {
  background-color: rgb(245,245,245);
}
p {text-align: center;}
h1{text-align: center;}
h2{text-align: center;}
body {
	background-image: url('https://www.desktopbackground.org/download/o/2015/06/10/962068_high-resolution-nature-spring-animal-squirrel-wallpapers-hd-18-full_1920x1080_h.jpg');
	background-attachment: fixed;
	background-size: cover;
}
</style>
</head>
<body>

<h1 style="color:Black;">Some Statistics about Sightings:</h1>

<p style="background-color:LightSkyBlue;color:White;font-size:15px;font-family:verdana">
	<table align=center>
			<tr>
				<td colspan="3">&nbsp;</td>
				<th scope="col">Result</th>
			</tr>
			<tr>
				<th colspan="3" scope="row">Total number of sightings</th>
				<td>{{ total_number }}</td>
			</tr>
			<tr>
                                <th colspan="3" scope="row">Number of AM shift sightings</th>
                                <td>{{ am_shift }}</td>
                        </tr>
			<tr>
                                <th colspan="3" scope="row">Number of sightings of adult squirrels</th>
				<td>{{ adult_count }}</td>
                        </tr>
			<tr>
                                <th colspan="3" scope="row">Number of sightings of grey squirrels</th>
                                <td>{{ gray_count }}</td>
                        </tr>
			<tr>
                                <th colspan="3" scope="row">Number of sightings of squirrels on the ground plane</th>
				<td>{{ ground_count }}</td>
                        </tr>
	</table>
</p>
<h2 style="color:Black;">Thank you for visiting our website!</h2>
<p><a href="{% url 'app:index' %}"><button type="button">Go Back to Index</button></a>
</p>
</body>
</html>

app/templates/app/update.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf8'>
    <style>
        body {
	    margin: 2;
	    font-family: cursive, sans-serif;
	    font-size:18px;
	    line-height:2;
	    color: DarkSlateGray;
	    background-image: url('https://wallpapermemory.com/uploads/786/squirrel-background-hd-1440x900-311648.jpg');
	    background-attachment: fixed;
	    background-size:cover;
	}
    </style>
</head>
<body>
    <h1 style="color: DarkSlateGray; font-family: cursive, sans-serif; line-height: 1;">Please Update Your Spot:</h1>
    <form method="post">
	{% csrf_token %}
        {% for field in form.visible_fields %}
        {{ field.help_text}}
        {{ field }}
	<br>
	{% endfor %}
        <br>
        <input type="submit" value="Update">
    </form>
    <p><a href="{% url 'app:index' %}"><button type="button">Go Back to Index</button></a></p> 
</body>
</html>